### ISSUE TITLE
大一寒假作业

### ISSUE THREAD

**Issue by marswong** [mis-lab/homework#1]
期末考试结束了，相信大家都有沉浸在假期的欣悦中了，吃 🐔的吃 🐔、晒 🐸的晒 🐸，不过不要忘了，要想在技术这条路上有收获，还是需要付出点 💦的（写代码），这个假期需要你们动手写一个小应用，可以是 Web 应用，也可以是客户端程序（包括控制台程序），总之要将你们所学的东西实践一遍（其实我知道考完期末试之后前面的都白学了 🙈），或者说花点时间重新学一遍。同时因为这次要求你们写一个应用了，在这个过程中你们通过自己摸索会学到很多新东西。废话少说了，下面是你们的作业题目（可以挑一个来做，也可以自己定一个题目）：

#### 要求

- 图形化界面
- 单人游戏
- 地图自己设定
- 地图中有白色石头墙(不能被子弹打坏, 子弹接触后消失)
- 地图中有红色石头墙(能被子弹打坏, 子弹接触后消失)
- 游戏结束条件: 1.基地标志被打坏 2.敌方坦克清空

#### 要求

- 图形化界面

#### 要求

- 图形化界面
- 全盘扫面、搜索文件
- 能在工具当中新建、删除文件
- 能在工具当中预览 txt 格式文件

#### 要求

- 实现 vim 当中 a i A I 的行内光标跳转功能
- 实现 vim 当中的 hjkl 切换光标的功能
- 实现 vim 当中 o O 插入行的功能
- 实现 vim 当中 指定行数跳转功能
- 实现 vim 当中 y 复制与 & p 粘贴功能

#### 要求

- 有一个报名页面用于填写报名信息
- 个人信息页面展示(如果报名成功则展示该用户信息, 同时可以也是查询用户报名信息的结果页面)
- 在个人信息页面取消报名
- 要求数据库保存信息
- 用 servlet 实现, jdbc 链接数据库
- tomcat 做 web 容器
- 不需要有具体页面信息, 但是所有的功能要在控制台上展示出来, 同时需要展示 mysql 当中的数据信息

#### 要求

- 有一个藏书展示模块, 展示书籍的借阅和剩余信息
- 图书借阅功能
- 图书归还功能
- 藏书销毁功能
- 新增藏书功能
- 用 servlet 实现, jdbc 连接数据库
- tomcat 做 web 容器
- 不强制要求有具体的容器实现, 但是所有的功能都要在控制台上展示出来, 同时需要展示 mysql 当中的数据信息

#### 要求

- 有博客界面和后台管理界面
- 支持博文的添加、删除、修改
- 支持博文分类
- 支持博文评论以及评论的回复（加分项）
- 支持博文的分享（加分项）
- 支持全文检索（加分项）

#### 要求

- 有论坛界面和后台管理界面
- 支持发帖、删帖、更新帖子以及帖子回复
- 支持帖子置顶
- 支持点赞
- 支持回复楼中楼（加分项）
- 会员权限（加分项）
- 小黑屋（加分项）

### 作业提交方式

这次作业要求大家用 github 来托管自己的代码，所以你首先需要有一个 github 账号（不要再问我怎么申请，我觉得这是 21 世纪一位互联网人的基本操作），有账号之后可以通过官方的[教程][github-guide]学习一下 github 的使用，然后创建你的仓库用来完成你的寒假作业。完成了寒假作业的小朋友可以来这里留言，留言的格式统一如下：

```
作品：XXX（你可以用作业的题目，不过既然是作品还是自己给起个有意思的名字吧）
作者：XXX、XXX（必须写上你的尊姓大名，不然我当你没交作业）
链接：XXX（将你的 github repo 的链接粘贴过来）
```

### 注意

* 这次的作业不分方向，同时也可以组队（最多两人一队），如果你觉得单挑很困难，可以组队完成（em，结对编程是一件很有意思的事情 😏），当然我是鼓励单挑的，单挑成功的小朋友可以找我要一个小惊喜。然后下学期开学你们每个人/小组都要展示自己的作品，得分最高的三位/组有奖励。
* 有问题了怎么办？要学会用搜索引擎，推荐[谷歌][google]或者必应[bing]；然后可以和小伙伴讨论，讨论学习效果很好，有解决方案的朋友也可以分享给大家；最后实在无解的时候可以去请教学长和学姐（优先骚扰大二的，不要一下子越级去骚扰大三大四的，你找我我只会给你一梭子，就酱 🙄）

最后，我知道你们此刻内心是奔溃的，不知道从何下手，放心，我已经为你们准备好了闯关秘籍，不要急着去写代码，掌握一些必要的基本理论才能让你事半功倍。如果你想做一个 Web 系统，却还不知道 Web 是什么的话，请按顺序将下面的教程啃完了：

1. [Web开发入门](https://developer.mozilla.org/zh-CN/docs/Learn/Getting_started_with_the_web)
2. [HTML入门](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML)
3. [CSS 介绍](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Introduction_to_CSS)
4. [JavaScript 第一步](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps)
5. [服务端网站编程的第一步](https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/First_steps)

Mozilla 社区做的教程浅显易懂，看完基本都可以写一个简单的网站，唯一的毛病就是翻译不完善，你需要借助搜索引擎去搜一下关键词来学习相关的内容。后端的同学肯定想问 Java 的教程在哪里，很抱歉 Java 社区在过去十多年一直很封闭，没有产出像 Mozilla 这样开放的社区，不过不用慌，没有文字教程，我们可以借助视频教程来学习相关的知识，[慕课网](https://www.imooc.com/) 上面的视频很丰富，相信会有和你胃口的。

最后的最后，祝大家寒假快乐 😃

[bing]: https://cn.bing.com
[google]: https://google.com
[github-guide]: https://guides.github.com

**Comment by MHeroBrine** [comment]
作品：五子棋人机大战
作者：王昊岩
链接：https://github.com/MHeroBrine/chess

**Comment by marswong** [comment]
@MHeroBrine 可以尝试一下 [Github Pages](https://pages.github.com/)，将你的作品变成一个可以在线运行的应用。

**Comment by Lbw1064416560** [comment]
作品：俄罗斯方块
作者：李博文
链接：https://github.com/Lbw1064416560/Winter-Work.git

**Comment by YuanLi126** [comment]
作品：简陋版坦克大战
作者：袁乙文
链接：https://github.com/YuanLi126/TankGame

**Comment by LumiereXyloto** [comment]
作品:俄罗斯方块
作者:李俭奇
链接:https://github.com/LumiereXyloto/github/tree/master/%E4%BF%84%E7%BD%97%E6%96%AF%E6%96%B9%E5%9D%97

**Comment by yuanxiru2** [comment]
作品：贪吃蛇
作者：袁夕入
链接：https://github.com/intelligenceFY/yuanxiri.git

**Comment by DreamofdogCai** [comment]
作品：坦克小小战
作者：肖杨
链接：https://github.com/DreamofdogCai/MyTankGame6.1

**Comment by xiaoTCOI** [comment]
作品：拼图小游戏
作者：田甜
链接：https://github.com/xiaoTCOI/xiaoTtx/tree/master/jigsaw%20puzzle

**Comment by Baowenj** [comment]
作品:苏宁易购首页
作者:包汶静
链接：https://github.com/Baowenj/homework

**Comment by kristem** [comment]
作品：博客系统
作者：蒋璐遥
链接：https://github.com/kristem/winterhomework

**Comment by marswong** [comment]
这次寒假作业的最终排名如下：

1. 袁乙文
2. 王昊岩
3. 李俭奇

这次很多同学都并列第四，没有得奖的同学请再接再厉，以上作业题目很多都可以作为业务的学习项目，加油：）
